const $=s=>document.querySelector(s),VW=640,VH=360,WW=2200,WH=1450;
const cv=$('#g'),dk=document.createElement('canvas'),dx=dk.getContext('2d');let ctx=cv.getContext('2d');
cv.width=dk.width=VW;cv.height=dk.height=VH;
const R=(a,b)=>a+Math.random()*(b-a),D=(a,b,c,d)=>Math.hypot(a-c,b-d),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
const PRI={rifle:{n:'Exorcist Rifle',c:150,d:75,r:1.2,m:5,p:1,s:.015,nz:420,sp:520,rl:2.2},shotgun:{n:'Hellbane Shotgun',c:130,d:15,r:1,m:2,p:7,s:.16,nz:380,sp:400,rl:2.4},repeater:{n:'Repeater',c:100,d:30,r:.38,m:8,p:1,s:.05,nz:340,sp:480,rl:2},crossbow:{n:'Silver Crossbow',c:60,d:55,r:1.4,m:1,p:1,s:.02,nz:60,sp:360,rl:1.8},pepperbox:{n:'Litany Pepperbox',c:140,d:21,r:.16,m:6,p:1,s:.09,nz:380,sp:480,rl:2.8},musket:{n:'Judgement Musket',c:200,d:140,r:1.9,m:2,p:1,s:.004,nz:520,sp:760,l:1,rl:3},flamer:{n:'Pyre Thrower',c:180,d:5,r:.1,m:40,p:2,s:.22,nz:130,sp:210,l:.38,rl:3.2},none:{n:'Fists & Faith',c:0}};
const SID={pistol:{n:'Pistol',c:50,d:24,r:.5,m:6,p:1,s:.06,nz:280,sp:460,rl:1.4},revolver:{n:"Saint's Revolver",c:85,d:40,r:.7,m:6,p:1,s:.04,nz:320,sp:480,rl:2},handcannon:{n:"Martyr's Cannon",c:130,d:75,r:1.1,m:3,p:1,s:.05,nz:430,sp:520,rl:2.2},whisper:{n:'Whisper Pistol',c:110,d:21,r:.45,m:8,p:1,s:.04,nz:45,sp:480,rl:1.5},none:{n:'Fists & Faith',c:0}};
Object.entries(PRI).forEach(([k,w])=>w.k=k);Object.entries(SID).forEach(([k,w])=>w.k=k);
const SKINS={plain:{f:'hunter',c:0,pl:1,n:'Plain Hunter',d:'Drab coat, bare face. Everyone starts somewhere.',coat:'#4a4640',coat2:'#5a564e',hood:'#3a3732',mask:'#c9a888',beak:'',eye:'',eyeg:'',rune:'',band:'#3a2e22'},
 warden:{f:'warden',c:0,n:'The Warden',d:'Hooded plague doctor. The order\'s standard.',coat:'#2b2433',coat2:'#3d3347',hood:'#1c1622',mask:'#d8d0c0',beak:'#c8bfa8',eye:'#ffd060',eyeg:'#ffb030',rune:'#ff3a2a',band:'#6a4a2a'},
 penitent:{f:'warden',c:450,n:'Crimson Penitent',d:'Robed in the blood of the fallen.',coat:'#5a1620',coat2:'#7a2230',hood:'#3a0c14',mask:'#e8e0d4',beak:'#d8cfc0',eye:'#ffffff',eyeg:'#ff7a7a',rune:'#ffd23a',band:'#2a1a1a'},
 ashen:{f:'warden',c:450,n:'Ashen Doctor',d:'Grey as the ash-fields. Eyes like marsh fire.',coat:'#3a3d40',coat2:'#505458',hood:'#26292b',mask:'#bfc4b8',beak:'#a9afa2',eye:'#a8ff70',eyeg:'#70e040',rune:'#70ff90',band:'#4a4a3a'},
 gravedigger:{f:'warden',c:550,n:'The Gravedigger',d:'Mud, rust and a long night of shovel work.',coat:'#4a3622',coat2:'#654a2e',hood:'#2e2012',mask:'#b89a78',beak:'#a4875f',eye:'#ffa040',eyeg:'#ff8a20',rune:'#ff8a20',band:'#2a1c10'},
 saint:{f:'warden',c:800,n:'Bone Saint',d:'Pale vestments. Heaven has not forgotten you.',coat:'#cfc8b8',coat2:'#e8e2d2',hood:'#a89f8a',mask:'#fff6dc',beak:'#efe4c4',eye:'#70c0ff',eyeg:'#4a9aff',rune:'#60b0ff',band:'#b89a50'},
 knight:{f:'knight',v:'knight',c:900,n:'Iron Crusader',d:'Plate, plume and a visor slit. Walks like a wall.',coat:'#8a8f9a',coat2:'#b4bac6',hood:'#5a5f6c',mask:'#000',beak:'',eye:'#ff5030',eyeg:'#ff3010',rune:'#7a1c24',band:'#d8b050'},
 gun:{f:'gun',v:'gun',c:700,n:'Dusk Gunslinger',d:'Duster, bandana and a hat that has seen worse nights.',coat:'#7a5a38',coat2:'#98704a',hood:'#3a2a1c',mask:'#d9b894',beak:'',eye:'#ffffff',eyeg:'#ffffff',rune:'#b02a2a',band:'#c8a050'},
 bones:{f:'bones',v:'bones',c:650,n:'Rattlebones',d:'Died once. Disliked it. Came back to hunt.',coat:'#e8e4d0',coat2:'#b8b4a0',hood:'#14101a',mask:'#f0ecd8',beak:'',eye:'#70ffd0',eyeg:'#30ffa0',rune:'#3a2a4a',band:'#6a5a8a'},
 witch:{f:'witch',v:'witch',c:750,n:'Bog Witch',d:'Tall hat, sharp nose, and a bottle of something awful.',coat:'#3a1a5a',coat2:'#5a2a82',hood:'#1c0e2e',mask:'#9ac47a',beak:'',eye:'#ffe040',eyeg:'#ffcc00',rune:'#ff5ad8',band:'#e0b040'},
 wolf:{f:'wolf',v:'wolf',c:800,n:'Wolfhide Stalker',d:'Pelt, paint and fangs. The wild hunts the breach.',coat:'#6a5a4a',coat2:'#9a8a74',hood:'#4a3e32',mask:'#d8b890',beak:'',eye:'#ffd040',eyeg:'#ffb000',rune:'#c02020',band:'#3a2a1c'},
 reaper:{f:'reaper',v:'reaper',c:0,led:1,mys:1,ep:1,n:'The Reaper',d:'Horns, wings, an ember where its heart should be, and a grin that never closes. How it is earned is not written anywhere.',coat:'#2a0b14',coat2:'#4a1626',hood:'#3c131e',mask:'#d8cca8',beak:'',eye:'#ffe060',eyeg:'#ffa020',rune:'#ff7a1a',band:'#6e1630'}};
const TOOL={tonic:{n:'Holy Water',c:20,d:'+50 HP (H) \u00b7 stacks to 3'},bomb:{n:'Blessed Charge',c:25,d:'big boom (G) \u00b7 stacks to 3'},flask:{n:'Hellfire Flask',c:35,d:'burning pool, 5s (Z) \u00b7 stacks to 3'},flare:{n:'Signal Flare',c:20,d:'lights the dark, lures imps (X) \u00b7 stacks to 3'},ward:{n:"Saint's Ward",c:40,d:'-60% damage for 10s (C) \u00b7 stacks to 3'}};
const XT=['flask','flare','ward','tripwire'],XL=['Flask','Flare','Ward','Wire'],TKS=['tonic','bomb',...XT];
TOOL.tripwire={n:'Tripwire',c:30,d:'plant a wire; anything that trips it \u2014 imps, rivals, even you \u2014 takes a blast (V) \u00b7 stacks to 3'};
const BOSS={gorrath:{n:'Gorrath the Maw',i:'\u{1F525}',d:'Charging brute of the pit.',bh:'charge',hp:900,bo:450},nyxara:{n:'Nyxara, Cinder Witch',i:'\u{1F608}',d:'Hurls hellfire from afar.',bh:'ranged',hp:650,bo:400},mordrek:{n:'Mordrek the Choir-Eater',i:'\u{1F47F}',d:'Calls the horde to his side.',bh:'summon',hp:750,bo:500}};
let bank=500,sel={skin:'plain',pri:'repeater',side:'pistol',tools:[{k:'tonic',n:2},null],bag:[]},boss='gorrath',mode='menu',walls=[],blds=[],trees=[],M=[],bul=[],eb=[],bombs=[],parts=[],clues=[],items=[],exts=[],P,cam={x:0,y:0},ground,blood,bx,keys={},mouse={x:320,y:180,l:0,r:0},msg='',msgT=0,shake=0,T=0,last=0,found=0,banished=0,corpse=null,bty=null,bn=null,mpHB=null,mpKB=null;
const FAMS={hunter:{n:'The Hunter',d:'The plain issue kit. Always yours.',c:0,def:'plain'},warden:{n:'The Warden',d:'Hooded plague doctor. 5 variations.',c:1000,def:'warden'},
 knight:{n:'Iron Crusader',d:'Plate, plume and a visor slit. Walks like a wall.',c:900,def:'knight'},
 gun:{n:'Dusk Gunslinger',d:'Duster, bandana and a hat that has seen worse nights.',c:700,def:'gun'},
 bones:{n:'Rattlebones',d:'Died once. Disliked it. Came back to hunt.',c:650,def:'bones'},
 witch:{n:'Bog Witch',d:'Tall hat, sharp nose, and a bottle of something awful.',c:750,def:'witch'},
 wolf:{n:'Wolfhide Stalker',d:'Pelt, paint and fangs. The wild hunts the breach.',c:800,def:'wolf'}};
const pit=q=>q.t=='f'?FAMS[q.k]:q.t=='w'?(SID[q.k]||PRI[q.k]||TOOL[q.k]):SKINS[q.k];
let pname='';const cleanName=v=>String(v==null?'':v).replace(/[^\w .'\-]/g,'').replace(/\s+/g,' ').trim().slice(0,14);
let LS={},AL=null,shopScr='shop',traps=[],own=['hunter','plain'],curFam='hunter',note='',pend=null,stash=[],invOpen=0;
const ISZ={rifle:[4,2],shotgun:[4,2],repeater:[3,2],crossbow:[3,2],pistol:[2,2],revolver:[2,2],tonic:[1,1],bomb:[2,1],pepperbox:[3,2],musket:[4,2],flamer:[3,2],handcannon:[2,2],whisper:[2,2],flask:[1,1],flare:[1,1],ward:[1,1],tripwire:[1,1]},SC=20,SR=8,MAXST=3,isz=k=>ISZ[k]||[1,1];
const fitsIn=(arr,C,R_,x,y,w,h,ex)=>x>=0&&y>=0&&x+w<=C&&y+h<=R_&&!arr.some(o=>{if(o===ex)return 0;const z=isz(o.k);return x<o.x+z[0]&&x+w>o.x&&y<o.y+z[1]&&y+h>o.y});
const spotIn=(arr,C,R_,k,ex)=>{const[w,h]=isz(k);for(let y=0;y<=R_-h;y++)for(let x=0;x<=C-w;x++)if(fitsIn(arr,C,R_,x,y,w,h,ex))return[x,y];return null};
const addTo=(arr,C,R_,k,n)=>{if(TOOL[k]){const t=arr.find(o=>o.k==k&&o.n<MAXST);if(t){t.n=Math.min(MAXST,t.n+(n||1));return 1}}const f=spotIn(arr,C,R_,k);if(!f)return 0;arr.push({k,x:f[0],y:f[1],n:n||(TOOL[k]?1:0)});return 1};
const fits=(x,y,w,h,ex)=>fitsIn(stash,SC,SR,x,y,w,h,ex),freeSpot=k=>spotIn(stash,SC,SR,k),addItem=(k,n)=>addTo(stash,SC,SR,k,n);
const accepts=(id,k)=>id=='p'?!!(PRI[k]&&k!='none'):id=='s'?!!(SID[k]&&k!='none'):!!TOOL[k];
const slotGet=id=>id=='p'?(sel.pri!='none'?{k:sel.pri}:null):id=='s'?(sel.side!='none'?{k:sel.side}:null):sel.tools[+id[1]]||null;
const slotSet=(id,it)=>{if(id=='p')sel.pri=it?it.k:'none';else if(id=='s')sel.side=it?it.k:'none';else sel.tools[+id[1]]=it?{k:it.k,n:it.n||1}:null};
const dsc=k=>TOOL[k]?TOOL[k].d:st(SID[k]||PRI[k]);
const SPX={rifle:[21,6.5,6],shotgun:[20,5,6],repeater:[19,5.5,7],crossbow:[19,5.5,17],pistol:[10,3,6],revolver:[17,6,7],tonic:[9,4.5,5],bomb:[12,6,5],pepperbox:[15,6,7],musket:[24,7,6],flamer:[21,6.5,7],handcannon:[16,5.5,7],whisper:[15,6,6],flask:[11,5.5,5],flare:[13,6,4],ward:[10,4,8]};
function itemCv(k,W,H){const c=document.createElement('canvas');c.width=W;c.height=H;c.style.cssText='width:100%;height:100%;image-rendering:pixelated;pointer-events:none';const[l,cx,h]=SPX[k]||[10,5,5],sc=Math.min(W*.86/l,H*.8/h),o=ctx;ctx=c.getContext('2d');try{drawWpn(k,W/2-cx*sc,H/2-.5*sc,0,sc)}finally{ctx=o}return c}
const SAVE=run=>{try{localStorage.setItem('bh_save',JSON.stringify({nm:pname,bank,own,led:LS,al:AL,skin:sel.skin,stash,pri:sel.pri,side:sel.side,bag:sel.bag,tools:sel.tools,run:run?1:0}))}catch(e){}};
try{const d=JSON.parse((localStorage.getItem('bh_save')||'null').replace(/"smg"/g,'"pepperbox"'));if(d&&Array.isArray(d.own)){own=[...new Set(['hunter','plain',...d.own.filter(k=>FAMS[k]||SKINS[k])])];bank=Math.max(120,d.bank|0);if(d.led)LS=d.led;AL=d.al||null;sel.skin=SKINS[d.skin]&&own.includes(d.skin)?d.skin:'plain';pname=cleanName(d.nm);
 const ok=k=>k&&k!='none'&&(PRI[k]||SID[k]);stash=[];(d.stash||[]).forEach(o=>{const k=typeof o=='string'?o:o&&o.k;if(!(ok(k)||TOOL[k]))return;const z=isz(k);if(typeof o=='object'&&Number.isInteger(o.x)&&Number.isInteger(o.y)&&fits(o.x,o.y,z[0],z[1]))stash.push({k,x:o.x,y:o.y,n:o.n||(TOOL[k]?2:0)});else addItem(k,o&&o.n)});
 if(d.run){sel.pri='none';sel.side='none';sel.bag=[];sel.tools=[null,null]}else{if(PRI[d.pri])sel.pri=d.pri;if(SID[d.side])sel.side=d.side;sel.bag=[];(Array.isArray(d.bag)?d.bag:d.bag?[d.bag]:[]).forEach(o=>{const k=typeof o=='string'?o:o&&o.k;if(!(ok(k)||TOOL[k]))return;const z=isz(k);if(typeof o=='object'&&Number.isInteger(o.x)&&Number.isInteger(o.y)&&fitsIn(sel.bag,4,4,o.x,o.y,z[0],z[1]))sel.bag.push({k,x:o.x,y:o.y,n:o.n||(TOOL[k]?1:0)});else addTo(sel.bag,4,4,k,o&&o.n)});if(Array.isArray(d.tools))sel.tools=[0,1].map(i=>{const t=d.tools[i];if(!t)return null;const k=typeof t=='string'?t:t.k;return TOOL[k]?{k,n:t.n||2}:null})}}}catch(e){}
